Build script for v2.11.0
revolut-mobile/TensorFlowLiteC-binary pull request #4
Opened 2023-02-13 17:55 UTC by agmike

2023-02-13 20:20 UTC, acecilia requested changes

2023-02-13 20:20 UTC, acecilia commented on scripts/make_xcframework.sh
> +    echo ""
Please remove empty echos around 🙏

2023-02-13 20:20 UTC, acecilia commented on scripts/make_xcframework.sh
> +    export JAVA_HOME="/opt/homebrew/opt/openjdk@11/libexec/openjdk.jdk/Contents/Home" && "${BAZEL_DIR}"/4.1.0/bazel build --incompatible_restrict_string_escapes=false -c opt //src:bazel
Can all changes in above function that is unrelated to 2.11.0 be rolled back?

2023-02-14 12:34 UTC, acecilia approved these changes

2023-02-14 12:44 UTC, barbasevich approved these changes

2023-02-14 15:04 UTC, merged